# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e826a78d5521768c8a9b9345039074147f53a536efaab99cf7666f945f068663dede03624e608c54eb79584daa2b4feb6b1da4f839645b503ee2e3978f250d17

test:
  secret_key_base: 9ef85da6496881250bc6cfc4c1b9485d5d03bb94fa0fb15248f76b69efb77620b23474fdbd59b7757416fb23c40b37cbe36f09410f5792edcbbd2ddf0f4a0c05

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
